config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    collection do
      get 'search'
      get 'detail_search'
      get 'create_search_selection'
      delete 'delete'
      get 'image'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :categories, only: [:show] do
    collection do
      get 'get_category_list'
    end
  end

  resource :mypages, only: [:show] do
    collection do
      get 'index'
      get 'logout'
      get 'myconfirmation'
      get 'selling_list'
      get 'likes_list'
    end
    member do
      get 'seller_product'
    end
  end

  resources :cards, only: [:index, :new, :create, :destroy] do
  end

  resources :users, only: [:create] do
    collection do
      get 'login'
      get 'sign_up'
      get 'user_registration'
      get 'user_registration_sns'
      get 'sms_confirmation'
      get 'address_registration'
      get 'card_registration'
      get 'registration_complete'
    end
  end

  resources :sessions, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

  get 'auth/:provider/callback', to: 'users#user_registration_sns'
  get 'auth/failure', to: 'users#login'

end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  has_one :sns_credential
  has_one :user_detail
  has_one :user_address
  accepts_nested_attributes_for :user_detail, :user_address
  has_many :likes
  has_many :products, through: :likes

  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ }

  has_secure_password validations: false
  validate(on: :update) do |record|
    record.errors.add(:password, :blank) unless record.password_digest.present?
  end
  validates_length_of :password, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED, on: :update
  validates_confirmation_of :password, allow_blank: true, on: :update
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_sign_in, only: :registration_complete
  before_action :save_to_session_address_registration, only: :address_registration
  before_action :save_to_session_card_registration, only: :card_registration
  before_action :access_payjp, only: [:create]
  layout 'users'

  def login
  end

  def sign_up
  end

  def user_registration
    @user = User.new
  end

  def user_registration_sns
    @user = User.new
    sns_email = request.env['omniauth.auth']['info']['email'] rescue nil
    sns_uid = request.env['omniauth.auth']['uid'] rescue nil
    sns_info = SnsCredential.find_by(uid: sns_uid)
    user = User.find_by(email: sns_email)
    if user && sns_info
      session[:user_id] = user.id
      redirect_to root_path
    else
      @sns_name = request.env['omniauth.auth']['info']['name'] rescue nil
      @sns_email = request.env['omniauth.auth']['info']['email'] rescue nil
      session[:provider] = request.env['omniauth.auth']['provider'] rescue nil
      session[:uid] = request.env['omniauth.auth']['uid'] rescue nil
    end
  end

  def sms_confirmation
  end

  def address_registration
    @user = User.new
    @user_detail = @user.build_user_detail
    @user_address = @user.build_user_address
  end

  def card_registration
  end

  def registration_complete
  end

  def create
    respond_to do |format|
      format.json{
        @user = User.new(
          nickname: session[:nickname],
          email: session[:email],
          password: session[:password],
          password_confirmation: session[:password_confirmation]
        )
        @user.build_user_detail(session[:user_detail_attributes])
        @user.build_user_address(session[:user_address_attributes])
        token = params[:token]
        response_customer = Payjp::Customer.create(
          card: token
        )
        card = response_customer.id
        @user.card_id = card
        if @user.save
          session[:user_id] = @user.id
        end
        if session[:uid]
          SnsCredential.create(
            user_id: @user.id,
            provider: session[:provider],
            uid: session[:uid]
          )
        end
      }
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :password_confirmation,
      user_detail_attributes: [
        :id,
        :last_name,
        :first_name,
        :last_name_kana,
        :first_name_kana
      ],
      user_address_attributes: [
        :id,
        :postal_code,
        :prefecture_id,
        :municipalitie,
        :address,
        :building_name
      ]
    )
  end

  # 条件チェック用のアクション
  # application_controllerのアクションをオーバーライド
  def use_search_header_category?
    false
  end

  def access_payjp
    require 'payjp'
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
  end

  def save_to_session_address_registration
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    @user = User.new(
      nickname: user_params[:nickname],
      email: user_params[:email],
      password: user_params[:password],
      password_confirmation: user_params[:password_confirmation]
    )
    unless @user.valid?
      if user_params[:password]
        render '/users/user_registration'
      else
        render '/users/user_registration_sns'
      end
    end
  end

  def save_to_session_card_registration
    @user = User.new
    session[:user_detail_attributes] = user_params[:user_detail_attributes]
    session[:user_address_attributes] = user_params[:user_address_attributes]
    @user_detail = @user.build_user_detail(session[:user_detail_attributes])
    @user_address = @user.build_user_address(session[:user_address_attributes])
    unless @user_detail.valid? && @user_address.valid?
      render '/users/address_registration'
    end
  end
end

app/views/users/address_registration.html.haml
%body
  .sign-up
    %header.sign-up__header
      %h1.sign-up__header__rogo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340", alt: "mercari", class: "sign-up__header__rogo__img"
      %nav.progress-bar
        %ol.progress-bar__container
          %li.progress-bar__container__list
            会員情報
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list
            電話番号認証
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list.active
            住所入力
            .progress-bar__container__list__progress-status.active-status
          %li.progress-bar__container__list
            支払い方法
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            完了
            .progress-bar__container__list__progress-status

    %main.sign-up__main
      %section.sign-up__main__container
        %h2.sign-up__main__container__head 住所入力
        .sign-up__main__container__body
          .sign-up__main__container__body__form
            = form_for @user, url: card_registration_users_path, method: :get, html: { id: :address_registration_form } do |f|
              = f.fields_for :user_detail do |d|
                .form-group
                  %label.form-label お名前
                  %span.form-require 必須
                  = d.text_field :first_name, placeholder: "例) 山田", class: "input-default"
                  = d.text_field :last_name, placeholder: "例) 彩", class: "input-default"
                .form-group
                  %label.form-label お名前カナ
                  %span.form-require 必須
                  = d.text_field :first_name_kana, placeholder: "例) ヤマダ", class: "input-default"
                  = d.text_field :last_name_kana, placeholder: "例) アヤ", class: "input-default"
              = f.fields_for :user_address do |a|
                .form-group
                  = a.label :postal_code, "郵便番号", class: "form-label"
                  %span.form-require 必須
                  = a.text_field :postal_code, placeholder: "例) 123-4567", class: "input-default"
                .form-group
                  = a.label :prefecture_code, "都道府県", class: "form-label"
                  %span.form-require 必須
                  .select-wrap
                    = a.collection_select(:prefecture_id, Prefecture.all, :id, :name, { prompt: "---" } , { class: "select-default"} )
                    %i.fa.fa-chevron-down
                .form-group
                  = a.label :municipalitie, "市区町村", class: "form-label"
                  %span.form-require 必須
                  = a.text_field :municipalitie, placeholder: "例) 横浜市緑区", class: "input-default"
                .form-group
                  = a.label :address, "番地", class: "form-label"
                  %span.form-require 必須
                  = a.text_field :address, placeholder: "例) 青山1−1−1", class: "input-default"
                .form-group
                  = a.label :building_name, "建物名", class: "form-label"
                  %span.form-arbitrary 任意
                  = a.text_field :building_name, placeholder: "例) 柳ビル103", class: "input-default"
              = f.submit "次へ進む", class: "btn-default btn-red"
= render "shared/sell-footer"

app/views/users/card_registration.html.haml
%head
  %script{src: "https://js.pay.jp/", type: "text/javascript"}

%body
  .sign-up
    %header.sign-up__header
      %h1.sign-up__header__rogo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340", alt: "mercari", class: "sign-up__header__rogo__img"
      %nav.progress-bar
        %ol.progress-bar__container
          %li.progress-bar__container__list
            会員情報
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list
            電話番号認証
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list
            住所入力
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list.active
            支払い方法
            .progress-bar__container__list__progress-status.active-status
          %li.progress-bar__container__list
            完了
            .progress-bar__container__list__progress-status

    %main.sign-up__main
      %section.sign-up__main__container
        %h2.sign-up__main__container__head 支払い方法
        = form_with url: users_path, method: "post" do |f|
          .sign-up__main__container__body
            .sign-up__main__container__body__form
              .form-group
                %label.form-label カード番号
                %span.form-require 必須
                = f.number_field :card_number, placeholder: "半角数字のみ", class: "input-default"
                %ul.signup-card-list
                  %li
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3856598694", width: "49", height: "20"
                  %li
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3856598694", width: "34", height: "20"
                  %li
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3856598694", width: "30", height: "20"
                  %li
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3856598694", width: "32", height: "20"
                  %li
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3856598694", width: "21", height: "20"
                  %li
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3856598694", width: "32", height: "20"
                  %li
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?3856598694", width: "32", height: "20"
              .form-group
                %label.form-label 有効期限
                %span.form-require 必須
                %br
                .select-wrap.year-month
                  = f.select :valid_month, [ ["---", "---"], ["1", "1"], ["2", "2"]], {}, {class: "select-default"}
                  %i.fa.fa-chevron-down
                %span 月
                %br
                .select-wrap.year-month
                  = f.select :valid_year, [ ["---", "---"], ["2020", "2020"], ["2019", "2019"], ["2018", "2018"]], {}, {class: "select-default"}
                  %i.fa.fa-chevron-down
                %span 年
              .form-group
                %label.form-label セキュリティコード
                %span.form-require 必須
                = f.number_field :security_code, placeholder: "カード背面4桁もしくは3桁の番号", class: "input-default"
              .security-code-message
                .security-code-message__text
                  %span.security-code-message__text__question ?
                  カード裏面の番号とは？
              = f.submit "次へ進む", class: "btn-default btn-red", id: "card-registration__btn"
= render "shared/sell-footer"

app/views/users/login.html.haml
= render "shared/sell-header"
%main.login__main
  %section.login__main__container
    .login__main__container__sign-up-form
      %p.login__main__container__sign-up-form__text アカウントをお持ちでない方はこちら
      = link_to "新規会員登録", sign_up_users_path, class: "btn-sign-up"
    .login__main__container__body
      .login__main__container__body__login-btn
        = link_to "/auth/facebook", class: "btn-default btn-sns btn-sns-facebook", method: :post do
          %i.fab.fa-facebook-square
          Facebookでログイン
        = link_to "/auth/google_oauth2", class: "btn-default btn-sns btn-sns-google", method: :post do
          = image_tag "https://img.icons8.com/color/50/000000/google-logo.png", class: "google-icon"
          Googleでログイン
    = form_for :session, url: sessions_path do |f|
      .login__main__container__bottom
        .form-group
          = f.email_field :email, placeholder: "メールアドレス", class: "input-default"
        .form-group
          = f.password_field :password, placeholder: "パスワード", class: "input-default login-form"
        = f.submit "ログイン", class: "btn-default btn-red login-submit"
        .password-forget
          = link_to "パスワードをお忘れの方", root_path, class: "password-forget__text"
= render "shared/sell-footer"

app/views/users/myconfirmation.html.haml
= render "products/product-create-link"
= render "products/main-header"
.flex-wrapper
  = render "/layouts/sidemenu"
  .mycontents-myconf
    %h2.myconf-title 本人情報の登録
    = form_with model: @user, class: "form-myconf", local: true do |f|
      .myconf-subtitle
        %p
          お客さまの本人情報をご登録ください。
          %br 登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        .myconf-right-link
          = link_to root_path, class: "link-brue-myconf" do
            .display-frex-myconf
              %h4 本人確認書類のアップロードについて
              %i.fas.fa-chevron-right
      .margin-myconf
        = f.label :お名前, class: "myconf-bold"
        %p 小室洸介
      .form-group-myconf
        = f.label :お名前カナ, class: "myconf-bold"
        %p コムロコウスケ
      .form-group-myconf
        = f.label :生年月日, class: "myconf-bold"
        %p 1996/11/3
      .form-group-myconf
        = f.label :郵便番号, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.text_field :adress, placeholder: "例）1234567", class: "input-myconf-default"
      .form-group-myconf.myconf-relative
        = f.label :都道府県, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.collection_select(:prefecture_id, Prefecture.all, :id, :prefecture, { prompt: "---" } , { class: "select-myconf-default"} )
        %i.fas.fa-chevron-down.myconf-absolute
      .form-group-myconf
        = f.label :市町村, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.text_field :adress, placeholder: "例)横浜市緑区", class: "input-myconf-default"
      .form-group-myconf
        = f.label :番地, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.text_field :adress, placeholder: "例）青山1-1-1", class: "input-myconf-default"
      .form-group-myconf
        = f.label :建物名, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.text_field :adress, placeholder: "例）柳ビル103", class: "input-myconf-default"
      = f.submit "登録する", class: "btn-myconf-default"
      .myconf-right-link.myconf-link-setting
        = link_to root_path, class: "link-brue-myconf" do
          .display-frex-myconf
            %h4 本人情報の登録について
            %i.fas.fa-chevron-right
= render "products/main-footer"

app/views/users/registration_complete.html.haml
%body
  .sign-up
    %header.sign-up__header
      %h1.sign-up__header__rogo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340", alt: "mercari", class: "sign-up__header__rogo__img"
      %nav.progress-bar
        %ol.progress-bar__container
          %li.progress-bar__container__list
            会員情報
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list
            電話番号認証
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list
            住所入力
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list
            支払い方法
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list.active
            完了
            .progress-bar__container__list__progress-status.active-status

    %main.sign-up__main
      %section.sign-up__main__container
        %h2.sign-up__main__container__head 会員登録完了
        .sign-up__main__container__body
          .sign-up__main__container__body__form
            .registered-message
              %p.registered-message__text
                ありがとうございます。
                %br 会員登録が完了しました。
            = link_to "メルカリを始める", root_path, class: "btn-default btn-red"
= render "shared/sell-footer"

app/views/users/sign_up.html.haml
= render "shared/sell-header"
%main.sign-up__main
  %section.sign-up__main__container
    %h2.sign-up__main__container__head 新規会員登録
    .sign-up__main__container__body
      .sign-up__main__container__body__form
        = link_to user_registration_users_path, class: "btn-default btn-mail" do
          %i.material-icons mail_outline
          メールアドレスで登録
        = link_to "/auth/facebook", class: "btn-default btn-sns btn-sns-facebook", method: :post do
          %i.fab.fa-facebook-square
          Facebookで登録
        = link_to "/auth/google_oauth2", class: "btn-default btn-sns btn-sns-google", method: :post do
          = image_tag "https://img.icons8.com/color/50/000000/google-logo.png", class: "google-icon"
          Googleで登録
= render "shared/sell-footer"

app/views/users/signup.html.haml
= render "shared/sell-header"
%main.sign-up__main
  %section.sign-up__main__container
    %h2.sign-up__main__container__head 新規会員登録
    .sign-up__main__container__body
      .sign-up__main__container__body__form
        = link_to user_registration_users_path, class: "btn-default btn-mail" do
          %i.material-icons mail_outline
          メールアドレスで登録
        %button.btn-default.btn-sns.btn-sns-facebook
          %i.fab.fa-facebook-square
          Facebookで登録
        %button.btn-default.btn-sns.btn-sns-google
          = image_tag "https://img.icons8.com/color/50/000000/google-logo.png", class: "google-icon"
          Googleで登録
= render "shared/sell-footer"

app/views/users/sms_confirmation.html.haml
%body
  .sign-up
    %header.sign-up__header
      %h1.sign-up__header__rogo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340", alt: "mercari", class: "sign-up__header__rogo__img"
      %nav.progress-bar
        %ol.progress-bar__container
          %li.progress-bar__container__list
            会員情報
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list.active
            電話番号認証
            .progress-bar__container__list__progress-status.active-status
          %li.progress-bar__container__list
            お届け先住所入力
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            支払い方法
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            完了
            .progress-bar__container__list__progress-status

    %main.sign-up__main
      %section.sign-up__main__container
        %h2.sign-up__main__container__head--tel-confirmation 電話番号の確認
        = form_with model: @user do |f|
          .sign-up__main__container__body--tel-confirmation
            .sign-up__main__container__body__form
              .form-group
                %label.form-label 携帯電話の番号
                = f.phone_field :phone_number, placeholder: "携帯電話の番号を入力", class: "input-default"
              %p.form-message 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
              = f.submit "SMSを送信する", class: "btn-default btn-red"
              %p.form-message ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
              .sign-up__main__container__body__form__confirmation
                = link_to root_path, target: "_blank", class: "sign-up__main__container__body__form__confirmation__text" do
                  %span 電話番号の確認が必要な理由
                  %i.fa.fa-chevron-right
= render "shared/sell-footer"

app/views/users/step1.html.haml
%body
  .sign-up
    %header.sign-up__header
      %h1.sign-up__header__rogo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340", alt: "mercari", class: "sign-up__header__rogo__img"
      %nav.progress-bar
        %ol.progress-bar__container
          %li.progress-bar__container__list.active
            会員情報
            .progress-bar__container__list__progress-status.active-status
          %li.progress-bar__container__list
            電話番号認証
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            お届け先住所入力
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            支払い方法
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            完了
            .progress-bar__container__list__progress-status

    %main.sign-up__main
      %section.sign-up__main__container
        %h2.sign-up__main__container__head 会員情報入力
        = form_with model: @user do |f|
          .sign-up__main__container__body
            .sign-up__main__container__body__form
              .form-group
                %label.form-label ニックネーム
                %span.form-require 必須
                = f.text_field :nickname, placeholder: "例) メルカリ太郎", class: "input-default"
              .form-group
                %label.form-label メールアドレス
                %span.form-require 必須
                = f.email_field :email, placeholder: "PC・携帯どちらでも可", class: "input-default"
              .form-group
                %label.form-label パスワード
                %span.form-require 必須
                = f.password_field :password, placeholder: "6文字以上", class: "input-default"
              .form-group
                %label.form-label パスワード(確認)
                %span.form-require 必須
                = f.password_field :password2, placeholder: "6文字以上", class: "input-default"
              = f.submit "次へ進む", class: "btn-default btn-red"
= render "shared/sell-footer"

app/views/users/step2.html.haml
%body
  .sign-up
    %header.sign-up__header
      %h1.sign-up__header__rogo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340", alt: "mercari", class: "sign-up__header__rogo__img"
      %nav.progress-bar
        %ol.progress-bar__container
          %li.progress-bar__container__list
            会員情報
            .progress-bar__container__list__progress-status.through
          %li.progress-bar__container__list.active
            電話番号認証
            .progress-bar__container__list__progress-status.active-status
          %li.progress-bar__container__list
            お届け先住所入力
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            支払い方法
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            完了
            .progress-bar__container__list__progress-status

    %main.sign-up__main
      %section.sign-up__main__container
        %h2.sign-up__main__container__head--tel-confirmation 電話番号の確認
        = form_with model: @user do |f|
          .sign-up__main__container__body--tel-confirmation
            .sign-up__main__container__body__form
              .form-group
                %label.form-label 携帯電話の番号
                = f.phone_field :phone_number, placeholder: "携帯電話の番号を入力", class: "input-default"
              %p.form-message 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
              = f.submit "SMSを送信する", class: "btn-default btn-red"
              %p.form-message ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
              .sign-up__main__container__body__form__confirmation
                = link_to root_path, target: "_blank", class: "sign-up__main__container__body__form__confirmation__text" do
                  %span 電話番号の確認が必要な理由
                  %i.fa.fa-chevron-right
= render "shared/sell-footer"

app/views/users/user_registration.html.haml
%body
  .sign-up
    %header.sign-up__header
      %h1.sign-up__header__rogo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340", alt: "mercari", class: "sign-up__header__rogo__img"
      %nav.progress-bar
        %ol.progress-bar__container
          %li.progress-bar__container__list.active
            会員情報
            .progress-bar__container__list__progress-status.active-status
          %li.progress-bar__container__list
            電話番号認証
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            お届け先住所入力
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            支払い方法
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            完了
            .progress-bar__container__list__progress-status

    %main.sign-up__main
      %section.sign-up__main__container
        %h2.sign-up__main__container__head 会員情報入力
        = form_for @user, url: address_registration_users_path, method: :get, html: { id: :user_registration_form } do |f|
          .sign-up__main__container__body
            .sign-up__main__container__body__form
              .form-group
                = f.label :nickname, "ニックネーム", class: "form-label"
                %span.form-require 必須
                = f.text_field :nickname, placeholder: "例) メルカリ太郎", class: "input-default", value: "#{@sns_name}"
              .form-group
                = f.label :email, "メールアドレス", class: "form-label"
                %span.form-require 必須
                = f.email_field :email, type: "email", placeholder: "PC・携帯どちらでも可", class: "input-default", value: "#{@sns_email}"
              .form-group
                = f.label :password, "パスワード", class: "form-label"
                %span.form-require 必須
                = f.password_field :password, placeholder: "6文字以上", class: "input-default", id: "sign-up-password"
              .form-group
                = f.label :password_confirmation, "パスワード(確認)", class: "form-label"
                %span.form-require 必須
                = f.password_field :password_confirmation, placeholder: "6文字以上", class: "input-default"
              = f.submit "次へ進む", class: "btn-default btn-red"
= render "shared/sell-footer"

app/views/users/user_registration_sns.html.haml
%body
  .sign-up
    %header.sign-up__header
      %h1.sign-up__header__rogo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340", alt: "mercari", class: "sign-up__header__rogo__img"
      %nav.progress-bar
        %ol.progress-bar__container
          %li.progress-bar__container__list.active
            会員情報
            .progress-bar__container__list__progress-status.active-status
          %li.progress-bar__container__list
            電話番号認証
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            お届け先住所入力
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            支払い方法
            .progress-bar__container__list__progress-status
          %li.progress-bar__container__list
            完了
            .progress-bar__container__list__progress-status

    %main.sign-up__main
      %section.sign-up__main__container
        %h2.sign-up__main__container__head 会員情報入力
        = form_for @user, url: address_registration_users_path, method: :get, html: { id: :user_registration_sns_form } do |f|
          .sign-up__main__container__body
            .sign-up__main__container__body__form
              - if @user.errors.any?
                - @user.errors.full_messages.each do |message|
                  = message
              .form-group
                = f.label :nickname, "ニックネーム", class: "form-label"
                %span.form-require 必須
                = f.text_field :nickname, placeholder: "例) メルカリ太郎", class: "input-default", value: "#{@sns_name}"
              .form-group
                = f.label :email, "メールアドレス", class: "form-label"
                %span.form-require 必須
                = f.email_field :email, type: "email", placeholder: "PC・携帯どちらでも可", class: "input-default", value: "#{@sns_email}"
              = f.submit "次へ進む", class: "btn-default btn-red"
= render "shared/sell-footer"