config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    collection do
      get 'search'
      get 'detail_search'
      get 'create_search_selection'
      delete 'delete'
      get 'image'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :categories, only: [:show] do
    collection do
      get 'get_category_list'
    end
  end

  resource :mypages, only: [:show] do
    collection do
      get 'index'
      get 'logout'
      get 'myconfirmation'
      get 'selling_list'
      get 'likes_list'
    end
    member do
      get 'seller_product'
    end
  end

  resources :cards, only: [:index, :new, :create, :destroy] do
  end

  resources :users, only: [:create] do
    collection do
      get 'login'
      get 'sign_up'
      get 'user_registration'
      get 'user_registration_sns'
      get 'sms_confirmation'
      get 'address_registration'
      get 'card_registration'
      get 'registration_complete'
    end
  end

  resources :sessions, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

  get 'auth/:provider/callback', to: 'users#user_registration_sns'
  get 'auth/failure', to: 'users#login'

end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  
  def logout
  end

  def myconfirmation
  end

  def show
  end

  def selling_list
    @products = Product.where('(seller_id = ?)', @current_user.id)
  end

  def seller_product
    @product = Product.find(params[:format])
  end

  def likes_list
    @products = @current_user.products
  end

end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/mypages/index.html.haml
- breadcrumb :mypages
.wrapper
  = render "/layouts/sidemenu"
  .mypage__main-contents
    .user-information
      .user-information__head
        = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png"
        %h2 もっち
        .user-information__head__number
          評価 0 出品数 0
      .user-information__tab
        .user-information__tab__notification
          %h3#notification お知らせ
        .user-information__tab__todo-list
          %h3#todo-list やることリスト
      .user-information__contents
        .item
          = image_tag "//static.mercdn.net/images/mercari_profile.png", class: "notification__image"
          .message
            .message__text 事務局から個別メッセージ「ログイン通知」
            = fa_icon "clock", class: "clock"
            .message__time 1時間前
          = fa_icon "angle-right"
        .item
          = image_tag "//static.mercdn.net/images/mercari_profile.png", class: "notification__image"
          .message
            .message__text 明日、50%還元お得チケットの有効期限が切れます！詳細を確認しましょう。
            = fa_icon "clock", class: "clock"
            .message__time 2時間前
          = fa_icon "angle-right"
        .item
          = image_tag "//static.mercdn.net/images/mercari_profile.png", class: "notification__image"
          .message
            .message__text 事務局から個別メッセージ「ログイン通知」
            = fa_icon "clock", class: "clock"
            .message__time 3時間前
          = fa_icon "angle-right"
        .item
          = image_tag "//static.mercdn.net/images/mercari_profile.png", class: "notification__image"
          .message
            .message__text 【出品はじめかたガイド】安心でかんたんに出品する方法をCHECKしてみよう！
            = fa_icon "clock", class: "clock"
            .message__time 4時間前
          = fa_icon "angle-right"
        .item
          = image_tag "//static.mercdn.net/images/mercari_profile.png", class: "notification__image"
          .message
            .message__text 《メルカリご登録記念》"最大500円分"をポイントバック！
            = fa_icon "clock", class: "clock"
            .message__time 5時間前
          = fa_icon "angle-right"
        .list
          .list__btn 
            %span 一覧を見る
    .transaction
      .transaction__head
        %h2 購入した商品
      .transaction__tab
        .transaction__tab__now
          %h3#transaction-now 取引中
        .transaction__tab__old
          %h3#transaction-old 過去の取引
      .transaction__contents
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3856598694"
        %h2 取引中の商品がありません
  .clear

app/views/mypages/likes_list.html.haml
- breadcrumb :likes
.wrapper
  = render "/layouts/sidemenu"
  .mypage__main-contents
    .likes-product
      .likes-product__head
        %h2 いいね！一覧
      .likes-product__contents
        - @products.each do |product|
          = link_to product_path(product.id) do
            .item
              = image_tag "#{product.images[0].url}", class: "product__image"
              .product
                .product__title
                  = product.name
                .product__price ¥ #{product.price}
              = fa_icon "angle-right"
  .clear

app/views/mypages/logout.html.haml
- breadcrumb :logout
.flex-wrapper
  = render "/layouts/sidemenu"
  .mycontents-logout
    = link_to session_path(@current_user.id), method: :delete do
      .logout-btn
        ログアウト

app/views/mypages/myconfirmation.html.haml
- breadcrumb :myconfirmation
.flex-wrapper
  = render "/layouts/sidemenu"
  .mycontents-myconf
    %h2.myconf-title 本人情報の登録
    = form_with model: @user, class: "form-myconf", local: true do |f|
      .myconf-subtitle
        %p
          お客さまの本人情報をご登録ください。
          %br 登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        .myconf-right-link
          = link_to root_path, class: "link-brue-myconf" do
            .display-frex-myconf
              %h4 本人確認書類のアップロードについて
              %i.fas.fa-chevron-right
      .margin-myconf
        = f.label :お名前, class: "myconf-bold"
        %p 小室洸介
      .form-group-myconf
        = f.label :お名前カナ, class: "myconf-bold"
        %p コムロコウスケ
      .form-group-myconf
        = f.label :生年月日, class: "myconf-bold"
        %p 1996/11/3
      .form-group-myconf
        = f.label :郵便番号, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.text_field :adress, placeholder: "例）1234567", class: "input-myconf-default"
      .form-group-myconf.myconf-relative
        = f.label :都道府県, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.collection_select(:prefecture_id, Prefecture.all, :id, :name, { prompt: "---" } , { class: "select-myconf-default"} )
        %i.fas.fa-chevron-down.myconf-absolute
      .form-group-myconf
        = f.label :市町村, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.text_field :adress, placeholder: "例)横浜市緑区", class: "input-myconf-default"
      .form-group-myconf
        = f.label :番地, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.text_field :adress, placeholder: "例）青山1-1-1", class: "input-myconf-default"
      .form-group-myconf
        = f.label :建物名, class: "myconf-bold"
        %span.arbitrary-form 任意
        = f.text_field :adress, placeholder: "例）柳ビル103", class: "input-myconf-default"
      = f.submit "登録する", class: "btn-myconf-default"
      .myconf-right-link.myconf-link-setting
        = link_to root_path, class: "link-brue-myconf" do
          .display-frex-myconf
            %h4 本人情報の登録について
            %i.fas.fa-chevron-right

app/views/mypages/seller_product.html.haml
.product-show-wrap{ data: { product_id: @product.id } }
  .product-showbox
    %h1.product-showbox__title
      = @product.name
    .product-showbox-contents
      .product-showbox-contents-slick
        .product-showbox-contents-slick__main-image
          - @product.images.each do |image|
            = image_tag ("#{image.url}"), class: "product-showbox-contents-slick__main-image--size"
        .product-showbox-contents-slick__thumbnail-image
          - @product.images.each do |image|
            = image_tag ("#{image.url}"), class: "product-showbox-contents-slick__thumbnail-image--size"
      .product-showbox-contents-detail
        .product-showbox-contents-detail-seller
          .product-showbox-contents-detail-seller__title
            %span
              出品者
          .product-showbox-contents-detail-seller__contents
            = link_to "#{@product.seller.nickname}", root_path, class:"product-showbox-contents-detail-seller__contents--name"
            .product-showbox-contents-detail-seller-evaluation
              %i.fa.fa-smile-o.product-showbox-contents-detail-seller-evaluation__icon-good
              29
              %i.fa.fa-meh-o.product-showbox-contents-detail-seller-evaluation__icon-normal
              1
              %i.fa.fa-frown-o.product-showbox-contents-detail-seller-evaluation__icon-bad
              0
        .product-showbox-contents-detail-category
          .product-showbox-contents-detail-category__title
            カテゴリー
          .product-showbox-contents-detail-category__contents
            -# サーバサイド実装時に変更: 表示している商品のカテゴリーへのリンクを貼る
            -# each.do使えそう
            = link_to root_path , class: "product-showbox-contents-detail-category__contents--link" do
              %i.fa.fa-chevron-right
              %span #{@product.category.parent.parent.name}
            = link_to root_path , class: "product-showbox-contents-detail-category__contents--link" do
              %i.fa.fa-chevron-right
              %span #{@product.category.parent.name}
            = link_to root_path , class: "product-showbox-contents-detail-category__contents--link" do
              %i.fa.fa-chevron-right
              %span #{@product.category.name}
        .product-showbox-contents-detail-brand
          .product-showbox-contents-detail-brand__title
            ブランド
          .product-showbox-contents-detail-brand__contents
            =link_to "#{@product.brand.brand}", root_path , class: "product-showbox-contents-detail-brand__contents--link"
        .product-showbox-contents-detail-size
          .product-showbox-contents-detail-size__title
            商品のサイズ
          .product-showbox-contents-detail-size__contents
            - if @product.size
              = @product.size.size
        .product-showbox-contents-detail-condition
          .product-showbox-contents-detail-condition__title
            商品の状態
          .product-showbox-contents-detail-condition__contents
            = @product.condition.condition
        .product-showbox-contents-detail-delivery-fee
          .product-showbox-contents-detail-delivery-fee__title
            配送料の負担
          .product-showbox-contents-detail-delivery-fee__contents
            = @product.delivery_method.parent.name
        .product-showbox-contents-detail-delivery-method
          .product-showbox-contents-detail-delivery-method__title
            配送の方法
          .product-showbox-contents-detail-delivery-method__contents
            = @product.delivery_method.name
        .product-showbox-contents-detail-delivery-source-area 
          .product-showbox-contents-detail-delivery-source-area__title
            配送元地域
          .product-showbox-contents-detail-delivery-source-area__contents
            =link_to "#{@product.prefecture.name}", root_path , class: "product-showbox-contents-detail-delivery-source-area__contents--link"
        .product-showbox-contents-detail-delivery-day
          .product-showbox-contents-detail-delivery-day__title
            発送日の目安
          .product-showbox-contents-detail-delivery-day__contents
            = @product.delivery_day.day
    .product-showbox-payment
      .product-showbox-payment__price
        ¥ #{@product.price}
        %span.product-showbox-payment__price--option-left
          (税込)
        %span.product-showbox-payment__price--option-right
          送料込み
    .product-showbox-description
      = @product.description
  .product-show-btn
    = link_to "商品の編集", edit_product_path(@product.id), class: "product-showbox-edit"
    .product-show-btn__text
      or
    = link_to "出品を再開する", root_path, class: "product-showbox-edit"
    .product-showbox-delete
      この商品を削除する
  .product-show-comment
    -# コメント機能実装時に変更
    - if true
      - 2.times do
        .product-show-comment-contents
          %i.fa.fa-user
          .product-show-comment-contents__detail
            .product-show-comment-contents__detail--name
              小室洸介
            .product-message
              .product-message__main-contents
                文字盤のサイズを教えてください。また、ベルトは穴にさすタイプですか？ベルト閉めたところも写真載せていただけると助かります。
              .product-message__sub-contents
                .product-message__sub-contents--time
                  %i.fa.fa-clock-o
                  %span 10時間前
                .product-message__sub-contents--report
                  %i.fa.fa-flag
    .product-show-comment-warning
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります
    -# コメント機能実装時に変更
    = form_with url: search_products_path, method: :get, class: :"product-show-comment-form", local: true do |f|
      = f.text_area :keyword, class: "product-show-comment-form__input"
      = f.submit "コメントする", class: "product-show-comment-form__button"

app/views/mypages/selling_list.html.haml
- breadcrumb :selling_list
.wrapper
  = render "/layouts/sidemenu"
  .mypage__main-contents
    .seller-product
      .seller-product__head
        %h2 出品した商品
      .seller-product__tab
        .seller-product__tab__selling
          %h3 出品中
        .seller-product__tab__trading
          %h3 取引中
        .seller-product__tab__sold
          %h3 売却済み
      .seller-product__contents
        - @products.each do |product|
          = link_to seller_product_mypages_path(product.id) do
            .item
              = image_tag "#{product.images[0].url}", class: "product__image"
              .product
                .product__title
                  = product.name
                = fa_icon "heart", class: "heart" 
                .product__likes #{product.likes.length}
                = fa_icon "comment-alt", class: "comment"
                .product__comments 0
              = fa_icon "angle-right"
  .clear

app/views/mypages/show.html.haml
- breadcrumb :profile
.flex-wrapper
  = render "/layouts/sidemenu"
  .mycontents
    %h2.myprof-title プロフィール
    = form_with model: @user, local: true do |f|
      .myprof-edit-top
        %figure
          = image_tag ("https://cdn.pixabay.com/photo/2019/05/23/19/29/dog-4224638__480.jpg"), class: "myprof-img"
        = f.text_field :nickname, placeholder: "例)AYA☆セール中", class: "input-myprof-default"
      .myprof-edit-bottom
        = f.text_area :descliption, placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", class: "textarea-myprof-default"
        = f.submit "変更する", class: "btn-myprof-default"