config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
  resources :products, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    collection do
      get 'search'
      get 'detail_search'
      get 'create_search_selection'
      delete 'delete'
      get 'image'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :categories, only: [:show] do
    collection do
      get 'get_category_list'
    end
  end

  resource :mypages, only: [:show] do
    collection do
      get 'index'
      get 'logout'
      get 'myconfirmation'
      get 'selling_list'
      get 'likes_list'
    end
    member do
      get 'seller_product'
    end
  end

  resources :cards, only: [:index, :new, :create, :destroy] do
  end

  resources :users, only: [:create] do
    collection do
      get 'login'
      get 'sign_up'
      get 'user_registration'
      get 'user_registration_sns'
      get 'sms_confirmation'
      get 'address_registration'
      get 'card_registration'
      get 'registration_complete'
    end
  end

  resources :sessions, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

  get 'auth/:provider/callback', to: 'users#user_registration_sns'
  get 'auth/failure', to: 'users#login'

end

app/views/layouts/_sidemenu.html.haml
.side-menu
  .mypage
    .item
      = link_to mypages_path do
        %span マイページ
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span お知らせ
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span やることリスト
        = fa_icon "angle-right"
    .item
      = link_to likes_list_mypages_path do
        %span いいね！一覧
        = fa_icon "angle-right"
    .item
      = link_to new_product_path do
        %span 出品する
        = fa_icon "angle-right"
    .item
      = link_to selling_list_mypages_path do
        %span 出品した商品 - 出品中
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span 出品した商品 - 取引中
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span 出品した商品 - 売却済み
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span 購入した商品 - 取引中
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span 購入した商品 - 過去の取引
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span ニュース一覧
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span 評価一覧
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span ガイド
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span お問い合わせ
        = fa_icon "angle-right"
  %h3 メルペイ
  .mypage.mer-pay
    .item
      = link_to mypages_path do
        %span 売上・振込申請
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span ポイント
        = fa_icon "angle-right"
  %h3 設定
  .mypage.setting
    .item
      = link_to '/mypages' do
        %span プロフィール
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span 発送元・お届け先住所変更
        = fa_icon "angle-right"
    .item
      = link_to cards_path do
        %span 支払い方法
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span メール/パスワード
        = fa_icon "angle-right"
    .item
      = link_to myconfirmation_mypages_path do
        %span 本人情報
        = fa_icon "angle-right"
    .item
      = link_to mypages_path do
        %span 電話番号の確認
        = fa_icon "angle-right"
    .item
      = link_to logout_mypages_path do
        %span ログアウト
        = fa_icon "angle-right"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample51b
    = favicon_link_tag('favicon.ico')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link(rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous")
    %link{rel:"stylesheet", type:"text/css", href:"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    %link{href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet"}
    %script{ type:"text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    = render "shared/sell-product-create-link"
    = render "shared/main-header" , header_category_parents: @header_category_parents
    - if (breadcrumbs != [])
      .breadwrap
        = breadcrumbs separator: " &rsaquo; ", style: :ul, class: "breadwrap__ul"
    = yield
    = render "shared/main-footer"

app/views/layouts/product-new.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample51b
    = favicon_link_tag('favicon.ico')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render "shared/sell-header"
    %main.sell-main
      .sellbox
        %h2.sellbox__title 商品の情報を入力
        = form_with model: @product, local: true, class: "sell-form" do |f|
          .sell-upload
            %h3.sell-upload__title
              出品画像
              %span.require-form 必須
            %p 最大10枚までアップロードできます
            .sell-dropbox
              .sell-dropbox__upload
                = f.file_field 'image', style: "display: none"
                %pre.sell-dropbox__text
                  ドラッグアンドドロップ
                  またはクリックしてファイルをアップロード
          .sell-content
            .sell-form-group
              %h3
                商品名
                %span.require-form 必須
              = f.text_field "name", class: "sell-input-default", placeholder: "商品名（必須 40文字まで)"
            .sell-form-group.sell-form-group-after
              %h3
                商品の説明
                %span.require-form 必須
              = f.text_area "description", class: "sell-textarea-default", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
          .sell-content.sell-flex
            %h3.sell-box-subtitle 商品の詳細
            .sell-form-box
              .sell-form-group#sell-category
                %h3
                  カテゴリー
                  %span.require-form 必須
                .sell-select-wrapper.sell-category-select
                  = select_tag "category", options_for_select(@category_parents), id: "sell-parent-category", class: "sell-select-default", include_blank: '---'
                  = f.hidden_field :category_id, value: "", class: "category"
                  %i.fas.fa-chevron-down
              .sell-size-brand
                .sell-form-group.sell-product-margin.sell-size-select
                .sell-form-group.sell-product-margin#sell-brand
                  %h3
                    ブランド
                    %span.arbitrary-form 任意
                  .none-box
                    = f.text_field "name", class: "sell-input-default", placeholder: "例) シャネル"
              .sell-form-group.sell-product-margin
                %h3
                  商品の状態
                  %span.require-form 必須
                .sell-select-wrapper
                  = f.collection_select( :condition_id, Condition.all, :id, :condition, { prompt: "---"}, {class: "sell-select-default"} )
                  %i.fas.fa-chevron-down
          .sell-content.sell-flex
            .sell-box-subtilte-flex
              %h3.sell-box-subtitle 配送について
              = link_to "？", root_path, class: "sell-form-question"
            .sell-form-box
              .sell-form-group
                %h3
                  配送料の負担
                  %span.require-form 必須
                .sell-select-wrapper
                  = f.select :delivery_fee_burden_id, [["送料込み(出品者負担)"], ["着払い(購入者負担)"]], {include_blank: '---'}, {id: "sell-delivery-burden", class: "sell-select-default"}
                  %i.fas.fa-chevron-down
              .sell-form-group.sell-product-margin.sell-delivery#seller-burden
                .sell-form-group
                %h3
                  配送方法
                  %span.require-form 必須
                .sell-select-wrapper
                  = f.select :name, [["未定"], ["らくらくメルカリ便"], ["ゆうパケット"], ["ゆうパック"], ["ゆうメール"], ["レターパック"], ["普通郵便(定形、定形外)"], ["クロネコヤマト"], ["クリップポスト"]], {include_blank: '---'}, {id: "sell-delivery-method", class: "sell-select-default"}
                  %i.fas.fa-chevron-down
              .sell-form-group.sell-product-margin.sell-delivery#buyer-burden
                .sell-form-group
                %h3
                  配送方法
                  %span.require-form 必須
                .sell-select-wrapper
                  = f.select :name, [["未定"], ["ゆうパック"], ["ゆうメール"], ["クロネコヤマト"]], {include_blank: '---'}, {id: "sell-delivery-method", class: "sell-select-default"}
                  %i.fas.fa-chevron-down
              .sell-form-group.sell-product-margin
                %h3
                  発送元の地域
                  %span.require-form 必須
                .sell-select-wrapper
                  = f.collection_select(:prefecture_id, Prefecture.all, :id, :name, { prompt: "---" } , { class: "sell-select-default"} )
                  %i.fas.fa-chevron-down
              .sell-form-group.sell-product-margin
                %h3
                  発送までの日数
                  %span.require-form 必須
                .sell-select-wrapper
                  = f.collection_select(:delivery_day_id, DeliveryDay.all , :id, :day, { prompt: "---"}, {class: "sell-select-default"})
                  %i.fas.fa-chevron-down
          .sell-content.sell-flex
            .sell-box-subtilte-flex
              %h3.sell-box-subtitle 販売価格(300〜9,999,999)
              = link_to "？", root_path, class: "sell-form-question"
            .sell-form-box
              %ul.sell-form-group
                %li.sell-money-flex
                  %h3.sell-label-left
                    価格
                    %span.require-form 必須
                  .sell-price-left ¥
                  .sell-price-right
                    = f.text_field "price", class: "sell-money-default", id: "product_price", placeholder: "例）300"
                %li.sell-fee
                  .sell-fee-left
                    販売手数料 (10%)
                  .sell-fee-right#list_right_tax -
                %li.sell-fee.sell-font-bold
                  .sell-fee-left
                    販売利益
                  .sell-fee-right.sell-font-big#list_right_price -
          .sell-content
            .sell-btnbox
              %p
                = link_to "禁止されている出品", root_path, class: "sell-link-blue"
                、
                = link_to "行為", root_path, class: "sell-link-blue"
                を必ずご確認ください。
              %p
                またブランド品でシリアルナンバー等がある場合はご記載ください。
                = link_to "偽ブランドの販売", root_path, class: "sell-link-blue"
                は犯罪であり処罰される可能性があります。
              %p
                また、出品をもちまして
                = link_to "加盟店規約", root_path, class: "sell-link-blue"
                に同意したことになります。
            = f.submit "出品する", class: "sell-btn-default"
            = link_to "もどる", root_path, class: "sell-btn-back"
    = render "shared/sell-footer"

app/views/layouts/sellproduct.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample51b
    = favicon_link_tag('favicon.ico')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link(rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous")
    %link{rel:"stylesheet", type:"text/css", href:"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    %link{href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet"}
    %script{ type:"text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    = render "shared/sell-header"
    = yield 
    = render "shared/sell-footer"

app/views/layouts/users.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample51b
    = favicon_link_tag('favicon.ico')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link(rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous")
    %link{rel:"stylesheet", type:"text/css", href:"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    %link{href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet"}
    %script{ type:"text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    = yield